# Generated by Django 4.2 on 2023-11-13 04:51

from django.db import migrations, models
import markdownx.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogBase', '0002_alter_article_content_alter_article_id_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=markdownx.models.MarkdownxField(max_length=1024),
        ),
    ]
