# Generated by Django 4.2 on 2023-11-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apply_followers',
            field=models.BooleanField(default=False),
        ),
    ]
